/*
 * myCBR License 3.0
 * 
 * Copyright (c) 2006-2015, by German Research Center for Artificial Intelligence (DFKI GmbH), Germany
 * 
 * Project Website: http://www.mycbr-project.net/
 * 
 * This library is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU Lesser General Public License as published by 
 * the Free Software Foundation; either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License 
 * along with this library; if not, write to the Free Software Foundation, Inc., 
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * 
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates. 
 * Other names may be trademarks of their respective owners.
 * 
 * endOfLic */

package test.junittest.load;
import no.ntnu.mycbr.core.Project;
import no.ntnu.mycbr.core.model.Concept;
import junit.framework.TestCase;

/**
 * tests the import functionality of XML files generated by myCBR v2.6.4 to < v3.0
 * 
 * @author myCBR Team
 * 
 */
public class RemoveInstances extends TestCase{

	public static void main(String args[]) {
		
		try {
			// load project

			String projectsPath = System.getProperty("user.dir") + "/src/test/projects/Web/";
			double start = System.currentTimeMillis();
			Project project = new Project(projectsPath + "used_cars_flat.zip");
			while (project.isImporting()) {
				
			}
			Concept modelClass = project.getConceptByID("Car");
			
			System.out.println("instances: " + modelClass.getAllInstances().size());
			modelClass.removeAllDirectInstances();
			System.out.println("instances after remove: " + modelClass.getAllInstances().size());
			
			
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
